config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations'}
  root to: "home#index"
  resources :profiles, only: [:show, :edit, :update]
  resources :articles, only: [:show, :new, :create, :edit, :update, :destroy] do
  resources :reviews, only: [:create, :destroy]
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :reviews, dependent: :delete_all

  mount_uploader :figure, FigureUploader

  validates :title, presence: true
  validates :category, presence: true
  validates :detail, presence: true

  enum category: {
    web: 1,
    mobile: 2,
    desk_top: 3
  }

  def self.inherited(klass)
    klass.class_eval do
      def self.categories_i18n
        categories_i18n
      end

      def category_i18n
        category_i18n[category]
      end
    end

    super
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :current_article, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def show
    @review = Review.new
    #退会したユーザーのレビューは表示させない
    @reviews = @article.reviews.joins(:user).includes(:user)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(create_params)

    if params[:back]
      render :new
    elsif @article.save
      flash[:success] = 'アイデアを投稿しました'
      redirect_to controller: :home, action: :index
    else
      render :new
    end

  end

  def edit
  end

  def update
    @article.update(update_params)

    if @article.save
      flash[:success] = 'アイデアを更新しました'
      redirect_to controller: :articles, action: :show
    else
      render :edit
    end

  end

  def destroy
    if @article.user_id == current_user.id
        @article.destroy
    end
    redirect_to controller: :home, action: :index
    flash[:success] = '投稿を削除しました'
  end

  private
  def create_params
    params.require(:article).permit(:title, :category, :detail, :cue, :feature, :point, :remark, :figure ).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:article).permit(:title, :category, :detail, :cue, :feature, :point, :remark, :figure ).merge(user_id: current_user.id)
  end

  #ログインユーザーが他ユーザーの情報を編集するパスを指定した場合はrootへリダイレクトする
  def correct_user
    redirect_to(root_path) unless current_user?(@article.user_id)
  end

  #選択したarticleのインスタンスを取得
  def current_article
      @article = Article.find(params[:id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def add_glyphicon_to_category(article)
    if article.category == "web"
      '<span class="glyphicon glyphicon-globe">' + article.category_i18n + '</span>'
    elsif article.category == "mobile"
      '<span class="glyphicon glyphicon-phone">' + article.category_i18n + '</span>'
    elsif article.category == "desk_top"
      '<span class="glyphicon glyphicon-home">' + article.category_i18n + '</span>'
    end
  end

end

app/views/articles/edit.html.erb
<% assign_meta_tags title: 'アイデアを編集' %>
<div class="container">
  <div class="row article-new">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="form-area">
      <br style="clear:both">
      <h3 style="margin-bottom: 25px; text-align: center;">アイデアを編集</h3>

        <!-- バリデーションを表示 -->
        <%= render 'shared/error_messages' %>

        <%= form_for(@article) do |f| %>

          <div class="form-group">
            <%= f.label :タイトル（必須）, autofocus: true %>
            <%= f.text_field :title, autofocus: true, class: 'form-control' ,placeholder:"タイトル" , :maxlength=>"20" %>
          </div>

          イメージ画像(モックアップ、設計図など)<small>画像部分をクリック、または画像をドラックアンドドロップしてください</small>
          <div class="cover-image-upload image-box article-edit" id="js-main-image">
            <%= image_tag(image_url(@article.figure.url), class: 'img-responsive image-preview-article') %>
            <%= f.file_field :figure %>
            <%= f.hidden_field :status, value: "main" %>
          </div>

          <div class="form-group">
            <%= f.label :開発するアプリケーション（必須）, autofocus: true %><br />
            <label>
              <%= f.radio_button :category, :web , :checked => "checked"%>
              <span class="glyphicon glyphicon-globe">Webアプリ</span>
            </label>
            <label>
              <%= f.radio_button :category, :mobile %>
              <span class="glyphicon glyphicon-phone">モバイルアプリ</span>
            </label>
            <label>
              <%= f.radio_button :category, :desk_top %>
              <span class="glyphicon glyphicon-home">デスクトップアプリ</span>
            </label>
          </div>

          <div class="form-group">
            <%= f.label :サービス内容（100字以内）（必須）, autofocus: true %>
            <%= f.text_area :detail, autofocus: true, class: 'form-control', id: 'message', placeholder:"プログラミング学習者がオリジナルのサービスやアプリケーションのアイデアを投稿できるサービスを作りたい" , :maxlength => "100", size: "100x2" %>
            <span class="help-block">
              <p id="characterLeft" class="help-block ">You have reached the limit</p>
            </span>
          </div>

          <div class="form-group">
            <%= f.label :このサービスをやろうとおもったきっかけ（400字数以内）, autofocus: true %>
            <%= f.text_area :cue, autofocus: true, class: 'form-control', id: 'message2', placeholder:"自分が思いついたアイデアが実力に見合っているのかが判断つかない。自分のアイデアに対して様々な人の意見が欲しい。他の人のアイデアを見て、自分のアイデアの参考にしたい。" , :maxlength => "400", size: "100x4" %>
            <span class="help-block">
              <p id="characterLeft2" class="help-block ">You have reached the limit</p>
            </span>
          </div>

          <div class="form-group">
            <%= f.label :実装したい重要な機能（1000字以内）, autofocus: true %>
            <%= f.text_area :feature, autofocus: true, class: 'form-control', id: 'message3', placeholder:"アイデアの編集(投稿・更新・削除・参照)できる機能、アカウント認証機能、マイページ機能" , :maxlength => "1000", size: "100x10" %>
            <span class="help-block">
              <p id="characterLeft3" class="help-block ">You have reached the limit</p>
            </span>
          </div>

          <div class="form-group">
            <%= f.label :重点的に力をいれてみたいポイント（1000字以内）, autofocus: true %>
            <%= f.text_area :point, autofocus: true, class: 'form-control', id: 'message4', placeholder:"コメント機能(投稿したアイデアに対して)は非同期通信(Ajax)を使いたい。ホーム画面にスライドショーを実装したい。" , :maxlength => "1000", size: "100x10" %>
            <span class="help-block">
              <p id="characterLeft4" class="help-block ">You have reached the limit</p>
            </span>
          </div>

          <div class="form-group">
            <%= f.label :備考欄（1000字以内）, autofocus: true %>
            <%= f.text_area :remark, autofocus: true, class: 'form-control', id: 'message5', placeholder:"補足したいことやこのアイデアを見ている人に伝えたいことを書いてみよう" , :maxlength => "1000", size: "100x10" %>
            <span class="help-block">
              <p id="characterLeft5" class="help-block ">You have reached the limit</p>
            </span>
          </div>
          <%= f.hidden_field :user_id %>
          <%= f.submit class:"btn btn-primary pull-right", value: '更新', data: {disable_with: 'Sending...'} %>
        <% end %>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<% assign_meta_tags title: '新規アイデア投稿' %>
<div class="container">
  <div class="row article-new">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="form-area">
        <br style="clear:both">
        <h3 style="margin-bottom: 25px; text-align: center;">新規アイデア投稿</h3>

        <%= form_for @article do |f| %>

        <!-- バリデーションを表示 -->
        <%= render 'shared/error_messages' %>

          <div class="form-group">
            <%= f.label :タイトル（必須）, autofocus: true %>
            <%= f.text_field :title, autofocus: true, class: 'form-control' ,placeholder:"タイトル" , :maxlength=>"20" %>
          </div>

          イメージ画像(モックアップ、設計図など)<small>画像部分をクリック、または画像をドラックアンドドロップしてください</small>
          <div class="cover-image-upload" id="js-main-image">
            <img class="image-preview-article"/>
            <%= f.file_field :figure %>
            <%= f.hidden_field :status, value: "main" %>
          </div>

          <div class="form-group">
            <%= f.label :開発するアプリケーション（必須）, autofocus: true %><br />
            <label>
              <%= f.radio_button :category, :web , :checked => "checked"%>
              <span class="glyphicon glyphicon-globe">Webアプリ</span>
            </label>
            <label>
              <%= f.radio_button :category, :mobile %>
              <span class="glyphicon glyphicon-phone">モバイルアプリ</span>
            </label>
            <label>
              <%= f.radio_button :category, :desk_top %>
              <span class="glyphicon glyphicon-home">デスクトップアプリ</span>
            </label>
          </div>

          <div class="form-group">
            <%= f.label :サービス内容（100字以内）（必須）, autofocus: true %>
            <%= f.text_area :detail, autofocus: true, class: 'form-control', id: 'message', placeholder:"プログラミング学習者がオリジナルのサービスやアプリケーションのアイデアを投稿できるサービスを作りたい" , :maxlength => "100", size: "100x2" %>
            <span class="help-block">
              <p id="characterLeft" class="help-block ">You have reached the limit</p>
            </span>
          </div>

          <div class="form-group">
            <%= f.label :このサービスをやろうとおもったきっかけ（400字数以内）, autofocus: true %>
            <%= f.text_area :cue, autofocus: true, class: 'form-control', id: 'message2', placeholder:"自分が思いついたアイデアが実力に見合っているのかが判断つかない。自分のアイデアに対して様々な人の意見が欲しい。他の人のアイデアを見て、自分のアイデアの参考にしたい。" , :maxlength => "400", size: "100x4" %>
            <span class="help-block">
              <p id="characterLeft2" class="help-block ">You have reached the limit</p>
            </span>
          </div>

          <div class="form-group">
            <%= f.label :実装したい重要な機能（1000字以内）, autofocus: true %>
            <%= f.text_area :feature, autofocus: true, class: 'form-control', id: 'message3', placeholder:"アイデアの編集(投稿・更新・削除・参照)できる機能、アカウント認証機能、マイページ機能" , :maxlength => "1000", size: "100x10" %>
            <span class="help-block">
              <p id="characterLeft3" class="help-block ">You have reached the limit</p>
            </span>
          </div>

          <div class="form-group">
            <%= f.label :重点的に力をいれてみたいポイント（1000字以内）, autofocus: true %>
            <%= f.text_area :point, autofocus: true, class: 'form-control', id: 'message4', placeholder:"コメント機能(投稿したアイデアに対して)は非同期通信(Ajax)を使いたい。ホーム画面にスライドショーを実装したい。" , :maxlength => "1000", size: "100x10" %>
            <span class="help-block">
              <p id="characterLeft4" class="help-block ">You have reached the limit</p>
            </span>
          </div>

          <div class="form-group">
            <%= f.label :備考欄（1000字以内）, autofocus: true %>
            <%= f.text_area :remark, autofocus: true, class: 'form-control', id: 'message5', placeholder:"補足したいことやこのアイデアを見ている人に伝えたいことを書いてみよう" , :maxlength => "1000", size: "100x10" %>
            <span class="help-block">
              <p id="characterLeft5" class="help-block ">You have reached the limit</p>
            </span>
          </div>

          <%= f.hidden_field :user_id %>

          <%= f.submit class:"btn btn-primary pull-right", value: '投稿する', data: {disable_with: 'Sending...'} %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<% assign_meta_tags title: "#{@article.title} " %>
<div class="container">
    <div class="article">
        <div class="row">
            <div class="col-lg-12">

                <div class="media">
                    <h1><%= @article.title %></h1>
                    <div class="media-body">
                        <p class="lead">
                            投稿者:<%= link_to "#{@article.user.profile.nickname_to_username}", profile_path(@article.user.profile.id) %>
                        </p>
                    </div>
                </div>
                <hr>

                <p class="glyphicon glyphicon-time" >投稿日:<%= l @article.created_at, format: :default %></p>
                <p class="glyphicon glyphicon-time" >最終更新日:<%= l @article.updated_at, format: :default %></p>
                <% if current_user?(@article.user_id) %>
                  <%= link_to '編集', edit_article_path(@article.id), class:"glyphicon glyphicon-edit" %>
                  <%= link_to '削除', article_path, class:"glyphicon glyphicon-trash text-danger", method: :delete, data: { confirm: 'この投稿を削除してもよろしいですか？' } %>
                <% end %>
                <hr>

                <%= image_tag(image_url(@article.figure.url), class:"img-responsive responsive-overwrite article-figure") %>
                <hr>

                <p class="lead">開発するアプリケーション<%= simple_format(add_glyphicon_to_category(@article)) %></p>
                <hr>

                <p class="lead">サービス内容<%= simple_format(@article.detail) %></p>
                <hr>

                <p class="lead">このサービスをやろうとおもったきっかけ<%= simple_format(@article.cue) %></p>
                <hr>

                <p class="lead">実装したい重要な機能<%= simple_format(@article.feature) %></p>
                <hr>

                <p class="lead">重点的に力をいれてみたいポイント<%= simple_format(@article.point) %></p>
                <hr>

                <p class="lead">備考欄<%= simple_format(@article.remark) %></p>
                <hr>

                <h4>コメント:</h4>
                <div class="media">
                    <div class="media-body">
                        <div class="comments">
                          <% if @reviews %>
                            <div id="reviews">
                              <%= render @reviews %>
                            </div>
                          <% end %>
                        </div>
                    </div>
                </div>
                <hr>

                <div class="well"">
                    <% if current_user %>
                        <div class="form-group">
                            <h4>コメントフォーム:</h4>
                            <%= form_for [@article, @review], remote: true do |f| %>
                                <%= f.text_area :comment, class: 'form-control', size: "100x5", id: "review_field", required: true %><br />
                                <%= f.submit "投稿する", class: "btn btn-primary withripple", data: {disable_with: 'Sending...'} %>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>