config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations'}
  root to: "home#index"
  resources :profiles, only: [:show, :edit, :update]
  resources :articles, only: [:show, :new, :create, :edit, :update, :destroy] do
  resources :reviews, only: [:create, :destroy]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.create(create_params)
    @article = Article.find(params[:article_id])
    @reviews = @article.reviews.joins(:user).includes(:user)
  end

  def destroy
    @article = Article.find(params[:article_id])
    review = @article.reviews.find(params[:id])
      if review.user_id == current_user.id
        review.destroy
      end
    @reviews = @article.reviews.joins(:user).includes(:user)
  end

  private
  def create_params
    params.require(:review).permit(:comment).merge(user_id: current_user.id, article_id: params[:article_id])
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
<div class="review-content">
  <div class="media-left">
    <%= link_to image_tag(image_url(review.user.profile.avatar.url), class:"review_user_profile_avatar"), profile_path(review.user.profile.id) %>
  </div>
  <div class="media-body">
    <h4 class="media-heading" id="top-aligned-media">
      <%= link_to simple_format("#{review.user.profile.nickname_to_username}") , profile_path(review.user.profile.id) %>
    </h4>
    <small>
      <p class="glyphicon glyphicon-time">
        <%= l review.created_at, format: :default %>
      </p>
      <% if current_user?(review.user_id) %>
        <%= link_to '削除', article_review_path(@article, review), method: :delete, remote: true, data: { confirm: 'このコメントを削除してもよろしいですか？'} %>
        <% end %>
    </small>
      <%= simple_format(review.comment) %>
  </div>
</div>

app/views/reviews/create.js.erb
$('#review_field').val('');

$('#reviews').html(
  "<%= j(render @reviews) %>"
);

app/views/reviews/destroy.js.erb
$('#reviews').html(
  "<%= j(render @reviews) %>"
);