config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations'}
  root to: "home#index"
  resources :profiles, only: [:show, :edit, :update]
  resources :articles, only: [:show, :new, :create, :edit, :update, :destroy] do
  resources :reviews, only: [:create, :destroy]
  end
end

app/views/common/_article.html.erb
<div class="col-sm-4 col-md-3 article-content">
  <div class="thumbnail">
    <%= link_to article_path(article.id) do %>
      <%= image_tag(image_url(article.figure.url), class:"article-thumbnail") %>
    <% end %>
    <div class="caption">
      <h3>
        <%= link_to article.title, article_path(article.id), class:"text-abbreviation" %>
      </h3>
      <div class="article-meta">
        <%= simple_format(add_glyphicon_to_category(article)) %>
        <%= simple_format(article.detail, class:"text-abbreviation") %>
        投稿者:<%= link_to article.user.profile.nickname_to_username, profile_path(article.user.profile.id), class:"text-abbreviation" %>
        <div class="article-posted">
          <%= simple_format("#{article.reviews.joins(:user).count}", class:"glyphicon glyphicon-comment") %>
          <p class="glyphicon glyphicon-time"><%= l article.updated_at, format: :default %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/common/_header.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">

      <!-- スマートフォンサイズで表示されるメニューボタンとテキスト -->
      <div class="navbar-header">
          <!-- ロゴをクリック時にホームへ移動 -->
          <%= link_to root_path, :class => 'navbar-brand' do %>
          <% end %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <!-- グローバルナビの中身 -->
      <div class="collapse navbar-collapse">
        <!-- 各ナビゲーションメニュー -->
        <ul class="nav navbar-nav navbar-right">
          <li>
              <%= link_to 'アイデアを投稿', new_article_path , class:"glyphicon glyphicon-edit" %>
          </li>
          <!-- ドロップダウンのメニュー -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag(image_url(current_user.profile.avatar.url), class:"avatar") %>
            </a>
            <ul class="dropdown-menu">
              <li>
                  <%= link_to 'マイページ', profile_path(current_user.profile.id) , class:"glyphicon glyphicon-user" %>
              </li>

              <li>
                  <%= link_to '設定', edit_user_registration_path, class:"glyphicon glyphicon-wrench" %>
              </li>

              <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out" %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/common/_login_logo.html.erb
<div class='sign_up_logo col-md-4 col-md-offset-4' align="center">
  <%= image_tag 'logo.png' %>
</div>

app/views/common/_sidebar.html.erb
<div class="col-sm-3 col-md-3">
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                      <span class="glyphicon glyphicon-wrench" aria-hidden="true">
                      </span> アカウント
<!--                     <span class="glyphicon glyphicon-folder-close">
                    </span>Content -->
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-wrench text-primary"></span>
                                    <%= link_to 'アカウント設定', edit_user_registration_path %>
                            </td>
                        </tr>
<!--                         <tr>
                            <td>

                            </td>
                        </tr> -->
<!--                         <tr>
                            <td>
                                <span class="glyphicon glyphicon-flash text-success"></span><a href="http://www.jquery2dotnet.com">News</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-file text-info"></span><a href="http://www.jquery2dotnet.com">Newsletters</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-comment text-success"></span><a href="http://www.jquery2dotnet.com">Comments</a>
                                <span class="badge">42</span>
                            </td>
                        </tr> -->
                    </table>
                </div>
            </div>
        </div>
<!--         <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                    </span>Modules</a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Invoices</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Shipments</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Tex</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div> -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">
                    </span>プロフィール</a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-user"></span>
                                <%#= link_to 'プロフィール設定', edit_profile_path %>
                                <%#= link_to 'プロフィール設定', "/profiles/1/edit" %>
                                <%#= link_to 'プロフィール設定', edit_profile_path(current_user.name_id) %>
                                <%= link_to 'プロフィール設定', edit_profile_path(current_user.profile.id) %>
                            </td>
                        </tr>
<!--                         <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Notifications</a> <span class="label label-info">5</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Import/Export</a>
                            </td>
                        </tr> -->

                    </table>
                </div>
            </div>
        </div>
<!--         <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-file">
                    </span>Reports</a>
                </h4>
            </div>
            <div id="collapseFour" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-usd"></span><a href="http://www.jquery2dotnet.com">Sales</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-user"></span><a href="http://www.jquery2dotnet.com">Customers</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-tasks"></span><a href="http://www.jquery2dotnet.com">Products</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-shopping-cart"></span><a href="http://www.jquery2dotnet.com">Shopping Cart</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div> -->
    </div>
</div>

app/views/common/_sign_up_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top sign-up-nav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-ex-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#signup-home">ホーム</a>
                </li>
                <li>
                    <a href="#signup-introduction">iDi(アイディ)とは</a>
                </li>
                <li>
                    <a href="#signup-feature">iDiでできること</a>
                </li>
                <li>
                    <a href="#signup-target">こんな人にオススメ</a>
                </li>
                <li>
                    <%= link_to 'ログイン', new_user_session_path %>
                </li>
            </ul>
        </div>
    </div>
</nav>